CREATE TABLE "Kantonsdaten" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kanton" TEXT NOT NULL,
    "miete" NUMERIC,
    "einkommen" NUMERIC
);

CREATE TABLE "Benutzer" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vorname" TEXT,
    "email" TEXT UNIQUE NOT NULL,
    "kanton" TEXT,
    "kantonsdaten_id" BIGINT REFERENCES "Kantonsdaten"("id") ON DELETE SET NULL
);

CREATE TABLE "Budget" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "monat" TEXT NOT NULL,
    "einkommen" NUMERIC DEFAULT 0,
    "ausgaben" NUMERIC DEFAULT 0,
    "benutzer_id" BIGINT REFERENCES "Benutzer"("id") ON DELETE CASCADE NOT NULL
);

CREATE TABLE "Transaktion" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "datum" DATE NOT NULL DEFAULT CURRENT_DATE,
    "typ" TEXT,
    "betrag" NUMERIC NOT NULL,
    "kategorie" TEXT,
    "benutzer_id" BIGINT REFERENCES "Benutzer"("id") ON DELETE CASCADE NOT NULL,
    "budget_id" BIGINT REFERENCES "Budget"("id") ON DELETE CASCADE
);

CREATE TABLE "Tipp" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "titel" TEXT NOT NULL,
    "inhalt" TEXT,
    "schwellenwert" NUMERIC,
    "kategorie" TEXT
);

CREATE TABLE "Budget_Tipp" (
    "budget_id" BIGINT REFERENCES "Budget"("id") ON DELETE CASCADE,
    "tipp_id" BIGINT REFERENCES "Tipp"("id") ON DELETE CASCADE,
    PRIMARY KEY ("budget_id", "tipp_id")
);